version: '3'
services:

  dbos:
    image: mysql
    volumes:
      - mysql_storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD : DB@123
      MYSQL_USER : phone
      MYSQL_DATABASE : phone
      MYSQL_PASSWORD : DB@123

  phonebook:
    image: phonebook
    volumes:
      - ./:/usr/local/apache2/htdocs/
    restart: always
    depends_on:
      - dbos
    ports:
      - 8080:80

volumes:
  mysql_storage: